### ISSUE TITLE
app_key

### ISSUE THREAD

**Issue by itsram90** [Rahulghuge94/finshoonya#1]
hey bro , im  new to all this, can you tell me how to obtain app_key to initiate the session

**Comment by Rahulghuge94** [comment]
basically i have written these over webapi when finvasia were not offerring api. now they are providing keys. if u want to use these library then go to developer tab and check quickauth requests. you will get appkey there in payload.
![image](https://user-images.githubusercontent.com/16452687/149670615-25c45bd8-a979-45da-a15e-06237e4b5b08.png)

**Comment by itsram90** [comment]
Brilliant

Thanks and Regards
Ram
________________________________
